modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ModdingForBlockheads/CookingForBlockheads/issues"

[[mods]]
modId="cookingforblockheads"
version="${file.jarVersion}"
displayName="CookingForBlockheads"
displayURL="https://blay09.net/mods/cookingforblockheads"
logoFile="cookingforblockheads-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Adds a cooking book and multiblock kitchens that only shows recipes you can make with what you currently have in your inventory.
'''

[[dependencies.cookingforblockheads]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"
[[dependencies.cookingforblockheads]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)"
ordering="NONE"
side="BOTH"
[[dependencies.cookingforblockheads]]
modId="balm"
mandatory=true
versionRange="[3.2.0,)"
ordering="NONE"
side="BOTH"
